#!/usr/bin/python3
# SPDX-FileCopyrightText: 2025 Seiya Ohata
# SPDX-License-Identifier: BSD-3-Clause

import sys

def main():
    counts = {}
    
    lines = sys.stdin.readlines()

    for line in lines:
        words = line.split()
        for w in words:
            if w in counts:
                counts[w] += 1
            else:
                counts[w] = 1


    for w, c in sorted(counts.items()):
        print(f"{w} {c}")

if __name__ == '__main__':
    main()
