#!/usr/bin/python3
import sys

# この関数を追加
def tonum(s):
    try:
        return int(s)
    except:
        return float(s)

ans = 0
for line in sys.stdin:
        # try-exceptブロックをこの関数呼び出しに変更
        ans += tonum(line)

print(ans)
